### ISSUE TITLE
API returning 500 Internal Server Error "MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017"

### ISSUE THREAD

**Issue by ayush-sharma** [TheKinrar/mastodon-instances#101]
I've been getting error 500 for almost 2 days now.
I'm not sure if the API isn't working for everyone or just me.

```
MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/home/instances/instances/node_modules/mongodb/lib/core/sdam/topology.js:448:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Can someone verify this please?

Link: https://instances.social/list

**Comment by TheKinrar** [comment]
Fixed, thanks!

**Comment by ayush-sharma** [comment]
Hey @TheKinrar, getting the same error today:

Can you have a look?

URL: `https://instances.social/api/1.0/instances/list`
```
MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/home/instances/instances/node_modules/mongodb/lib/core/sdam/topology.js:448:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by TheKinrar** [comment]
Fixed again. I've identified the root cause so it should not happen anymore

**Comment by TheKinrar** [comment]
I believe I missclicked
